adb -s emulator-5554 shell am broadcast -n com.android.providers.media/com.android.providers.media.MediaScannerReceiver
adb -s emulator-5554 shell am broadcast -n com.android.providers.media/com.android.providers.media.MediaUpgradeReceiver
adb -s emulator-5554 shell am broadcast -n com.android.providers.media/com.android.providers.media.MtpReceiver
adb -s emulator-5554 shell am broadcast -n com.android.inputdevices/com.android.inputdevices.InputDeviceReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.home.BootCompletedReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.home.GpsActivityReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.home.setup.SkipSetupReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.home.speech.SpeechBroadcastReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.logging.WearableAppLoggerGservicesReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.now.NowDeleteIntentReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.packagemanager.PackageUpdateReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.settings.GservicesChangedReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.settings.SendAmbientEnabledReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.stream.NotificationSideChannelReceiver
adb -s emulator-5554 shell am broadcast -n com.android.development/com.android.development.BadBehaviorActivity$BadReceiver
adb -s emulator-5554 shell am broadcast -n com.android.bluetooth/com.android.bluetooth.opp.BluetoothOppHandoverReceiver
adb -s emulator-5554 shell am broadcast -n com.android.bluetooth/com.android.bluetooth.opp.BluetoothOppReceiver
adb -s emulator-5554 shell am broadcast -n com.android.bluetooth/com.android.bluetooth.pbap.BluetoothPbapReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.apps.wearable.bugreportsender/com.google.android.clockwork.bugreportsender.BugReportStartReceiver
adb -s emulator-5554 shell am broadcast -n com.android.providers.calendar/com.android.providers.calendar.CalendarDebugReceiver
adb -s emulator-5554 shell am broadcast -n com.android.providers.calendar/com.android.providers.calendar.CalendarProviderBroadcastReceiver
adb -s emulator-5554 shell am broadcast -n com.android.providers.calendar/com.android.providers.calendar.CalendarReceiver
adb -s emulator-5554 shell am broadcast -n com.android.providers.calendar/com.android.providers.calendar.CalendarUpgradeReceiver
adb -s emulator-5554 shell am broadcast -n com.android.providers.downloads/com.android.providers.downloads.DownloadReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.checkin.CheckinService$Receiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.checkin.CheckinService$SecretCodeReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.checkin.CheckinService$TriggerReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.checkin.EventLogService$Receiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.gservices.GservicesProvider$OverrideReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.gtalkservice.DataMessageReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.gtalkservice.SendXmppReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.gtalkservice.ServiceAutoStarter
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.gtalkservice.XmppEndpointReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.gtalkservice.diagnostics.GTalkDiagnosticsBroadcastReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.loginservice.MigrateToAccountManagerBroadcastReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.loginservice.ServicesWatcher
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.settings.ConfirmLgaaylActivity$LaunchingLocationSettingsReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.settings.GoogleLocationSettings$LocationSettingsChangedListener
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.subscribedfeeds.SubscribedFeedsGCMBroadcastReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.update.SystemUpdateService$Receiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.update.SystemUpdateService$SecretCodeReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gsf/com.google.android.gsf.usagestats.StatsUploadService$Receiver
adb -s emulator-5554 shell am broadcast -n com.google.android.apps.wearable.setup/com.google.android.clockwork.setup.PairRequestReceiver
adb -s emulator-5554 shell am broadcast -n com.android.providers.contacts/com.android.providers.contacts.ContactsUpgradeReceiver
adb -s emulator-5554 shell am broadcast -n com.android.providers.contacts/com.android.providers.contacts.LocaleChangeReceiver
adb -s emulator-5554 shell am broadcast -n com.android.providers.contacts/com.android.providers.contacts.PackageIntentReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.BluetoothCompanionReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.BluetoothConnectabilityEnsuringReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.BootReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.GlobalKeyReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.GpsActivityReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.RetailTimeReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.SetLGAAYLReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.deskclock/com.google.android.deskclock.BootCompletedReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.deskclock/com.google.android.deskclock.TimeZoneChangeListener
adb -s emulator-5554 shell am broadcast -n com.android.netspeed/com.android.netspeed.NetSpeedBroadcastReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.analytics.internal.GServicesChangedReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.auth.authzen.GcmReceiverService$Receiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.auth.be.change.LoginAccountsChangedWakefulBroadcastReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.auth.be.proximity.authorization.AccountChangeProcessingService$AccountChangeReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.auth.be.proximity.authorization.bt.AuthorizationBluetoothService$AutoStarter
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.auth.be.proximity.authorization.bt.AuthorizationBluetoothService$BluetoothStateChangeReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.auth.be.recovery.AccountRecoveryBackgroundService$Receiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.auth.devicesignals.LockScreenListener
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.checkin.CheckinService$ActiveReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.checkin.CheckinService$ImposeReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.checkin.CheckinService$Receiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.checkin.CheckinService$SecretCodeReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.checkin.CheckinService$TriggerReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.checkin.EventLogService$Receiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.common.download.DownloadAlarmReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.common.download.DownloadCompleteReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.common.notification.PersistentNotificationBroadcastReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.common.receiver.InternalBroadcastReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.common.status.StatusServiceLauncherBroadcastReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.config.ConfigFetchService$PackageReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.fitness.service.AccountsChangedReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.fitness.service.FitnessInitReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.fitness.wearables.WearableSyncServiceReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.gcm.GcmDiagnosticsReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.gcm.GcmPackageTracker$GcmPackageChangeReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.gcm.GcmReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.gcm.GcmSenderProxy
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.gcm.GmsAutoStarter
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.gcm.ServiceAutoStarter
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.gcm.gmsproc.GroupRegisterReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.gcm.nts.SchedulerInternalReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.gcm.nts.SchedulerReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.playlog.service.MonitorAlarmReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.subscribedfeeds.ConfigurationReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.update.SystemUpdateService$ActiveReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.update.SystemUpdateService$Receiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.update.SystemUpdateService$SecretCodeReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.wearable.init.InitializeGmsWearableReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.gms.wearable.service.AutoStarterReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.location.internal.NlpNetworkProviderSettingsUpdateReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.location.network.ConfirmAlertActivity$LocationModeChangingReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.location.network.LocationProviderChangeReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.location.places.ImplicitSignalsReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.location.reporting.service.ExternalChangeReceiver
adb -s emulator-5554 shell am broadcast -n com.google.android.gms/com.google.android.location.reporting.service.GcmBroadcastReceiver
adb -s emulator-5554 shell am broadcast -n com.android.shell/com.android.shell.BugreportReceiver
adb -s emulator-5554 shell am broadcast -n android/com.android.server.BootReceiver
adb -s emulator-5554 shell am broadcast -n android/com.android.server.MasterClearReceiver
adb -s emulator-5554 shell am broadcast -n android/com.android.server.updates.CarrierProvisioningUrlsInstallReceiver
adb -s emulator-5554 shell am broadcast -n android/com.android.server.updates.CertPinInstallReceiver
adb -s emulator-5554 shell am broadcast -n android/com.android.server.updates.IntentFirewallInstallReceiver
adb -s emulator-5554 shell am broadcast -n android/com.android.server.updates.SELinuxPolicyInstallReceiver
adb -s emulator-5554 shell am broadcast -n android/com.android.server.updates.SmsShortCodesInstallReceiver
adb -s emulator-5554 shell am broadcast -n android/com.android.server.updates.TZInfoInstallReceiver
