 am broadcast -n com.android.providers.media/com.android.providers.media.MediaScannerReceiver
 am broadcast -n com.android.providers.media/com.android.providers.media.MediaUpgradeReceiver
 am broadcast -n com.android.providers.media/com.android.providers.media.MtpReceiver
 am broadcast -n com.android.inputdevices/com.android.inputdevices.InputDeviceReceiver
 am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.home.BootCompletedReceiver
 am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.home.GpsActivityReceiver
 am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.home.setup.SkipSetupReceiver
 am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.home.speech.SpeechBroadcastReceiver
 am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.logging.WearableAppLoggerGservicesReceiver
 am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.now.NowDeleteIntentReceiver
 am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.packagemanager.PackageUpdateReceiver
 am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.settings.GservicesChangedReceiver
 am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.settings.SendAmbientEnabledReceiver
 am broadcast -n com.google.android.wearable.app/com.google.android.clockwork.stream.NotificationSideChannelReceiver
 am broadcast -n com.android.development/com.android.development.BadBehaviorActivity$BadReceiver
 am broadcast -n com.android.bluetooth/com.android.bluetooth.opp.BluetoothOppHandoverReceiver
 am broadcast -n com.android.bluetooth/com.android.bluetooth.opp.BluetoothOppReceiver
 am broadcast -n com.android.bluetooth/com.android.bluetooth.pbap.BluetoothPbapReceiver
 am broadcast -n com.google.android.apps.wearable.bugreportsender/com.google.android.clockwork.bugreportsender.BugReportStartReceiver
 am broadcast -n com.android.providers.calendar/com.android.providers.calendar.CalendarDebugReceiver
 am broadcast -n com.android.providers.calendar/com.android.providers.calendar.CalendarProviderBroadcastReceiver
 am broadcast -n com.android.providers.calendar/com.android.providers.calendar.CalendarReceiver
 am broadcast -n com.android.providers.calendar/com.android.providers.calendar.CalendarUpgradeReceiver
 am broadcast -n com.android.providers.downloads/com.android.providers.downloads.DownloadReceiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.checkin.CheckinService$Receiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.checkin.CheckinService$SecretCodeReceiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.checkin.CheckinService$TriggerReceiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.checkin.EventLogService$Receiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.gservices.GservicesProvider$OverrideReceiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.gtalkservice.DataMessageReceiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.gtalkservice.SendXmppReceiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.gtalkservice.ServiceAutoStarter
 am broadcast -n com.google.android.gsf/com.google.android.gsf.gtalkservice.XmppEndpointReceiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.gtalkservice.diagnostics.GTalkDiagnosticsBroadcastReceiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.loginservice.MigrateToAccountManagerBroadcastReceiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.loginservice.ServicesWatcher
 am broadcast -n com.google.android.gsf/com.google.android.gsf.settings.ConfirmLgaaylActivity$LaunchingLocationSettingsReceiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.settings.GoogleLocationSettings$LocationSettingsChangedListener
 am broadcast -n com.google.android.gsf/com.google.android.gsf.subscribedfeeds.SubscribedFeedsGCMBroadcastReceiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.update.SystemUpdateService$Receiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.update.SystemUpdateService$SecretCodeReceiver
 am broadcast -n com.google.android.gsf/com.google.android.gsf.usagestats.StatsUploadService$Receiver
 am broadcast -n com.google.android.apps.wearable.setup/com.google.android.clockwork.setup.PairRequestReceiver
 am broadcast -n com.android.providers.contacts/com.android.providers.contacts.ContactsUpgradeReceiver
 am broadcast -n com.android.providers.contacts/com.android.providers.contacts.LocaleChangeReceiver
 am broadcast -n com.android.providers.contacts/com.android.providers.contacts.PackageIntentReceiver
 am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.BluetoothCompanionReceiver
 am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.BluetoothConnectabilityEnsuringReceiver
 am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.BootReceiver
 am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.GlobalKeyReceiver
 am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.GpsActivityReceiver
 am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.RetailTimeReceiver
 am broadcast -n com.google.android.apps.wearable.settings/com.google.android.clockwork.settings.SetLGAAYLReceiver
 am broadcast -n com.google.android.deskclock/com.google.android.deskclock.BootCompletedReceiver
 am broadcast -n com.google.android.deskclock/com.google.android.deskclock.TimeZoneChangeListener
 am broadcast -n com.android.netspeed/com.android.netspeed.NetSpeedBroadcastReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.analytics.internal.GServicesChangedReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.auth.authzen.GcmReceiverService$Receiver
 am broadcast -n com.google.android.gms/com.google.android.gms.auth.be.change.LoginAccountsChangedWakefulBroadcastReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.auth.be.proximity.authorization.AccountChangeProcessingService$AccountChangeReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.auth.be.proximity.authorization.bt.AuthorizationBluetoothService$AutoStarter
 am broadcast -n com.google.android.gms/com.google.android.gms.auth.be.proximity.authorization.bt.AuthorizationBluetoothService$BluetoothStateChangeReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.auth.be.recovery.AccountRecoveryBackgroundService$Receiver
 am broadcast -n com.google.android.gms/com.google.android.gms.auth.devicesignals.LockScreenListener
 am broadcast -n com.google.android.gms/com.google.android.gms.checkin.CheckinService$ActiveReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.checkin.CheckinService$ImposeReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.checkin.CheckinService$Receiver
 am broadcast -n com.google.android.gms/com.google.android.gms.checkin.CheckinService$SecretCodeReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.checkin.CheckinService$TriggerReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.checkin.EventLogService$Receiver
 am broadcast -n com.google.android.gms/com.google.android.gms.common.download.DownloadAlarmReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.common.download.DownloadCompleteReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.common.notification.PersistentNotificationBroadcastReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.common.receiver.InternalBroadcastReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.common.status.StatusServiceLauncherBroadcastReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.config.ConfigFetchService$PackageReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.fitness.service.AccountsChangedReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.fitness.service.FitnessInitReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.fitness.wearables.WearableSyncServiceReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.gcm.GcmDiagnosticsReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.gcm.GcmPackageTracker$GcmPackageChangeReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.gcm.GcmReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.gcm.GcmSenderProxy
 am broadcast -n com.google.android.gms/com.google.android.gms.gcm.GmsAutoStarter
 am broadcast -n com.google.android.gms/com.google.android.gms.gcm.ServiceAutoStarter
 am broadcast -n com.google.android.gms/com.google.android.gms.gcm.gmsproc.GroupRegisterReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.gcm.nts.SchedulerInternalReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.gcm.nts.SchedulerReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.playlog.service.MonitorAlarmReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.subscribedfeeds.ConfigurationReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.update.SystemUpdateService$ActiveReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.update.SystemUpdateService$Receiver
 am broadcast -n com.google.android.gms/com.google.android.gms.update.SystemUpdateService$SecretCodeReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.wearable.init.InitializeGmsWearableReceiver
 am broadcast -n com.google.android.gms/com.google.android.gms.wearable.service.AutoStarterReceiver
 am broadcast -n com.google.android.gms/com.google.android.location.internal.NlpNetworkProviderSettingsUpdateReceiver
 am broadcast -n com.google.android.gms/com.google.android.location.network.ConfirmAlertActivity$LocationModeChangingReceiver
 am broadcast -n com.google.android.gms/com.google.android.location.network.LocationProviderChangeReceiver
 am broadcast -n com.google.android.gms/com.google.android.location.places.ImplicitSignalsReceiver
 am broadcast -n com.google.android.gms/com.google.android.location.reporting.service.ExternalChangeReceiver
 am broadcast -n com.google.android.gms/com.google.android.location.reporting.service.GcmBroadcastReceiver
 am broadcast -n com.android.shell/com.android.shell.BugreportReceiver
 am broadcast -n android/com.android.server.BootReceiver
 am broadcast -n android/com.android.server.MasterClearReceiver
 am broadcast -n android/com.android.server.updates.CarrierProvisioningUrlsInstallReceiver
 am broadcast -n android/com.android.server.updates.CertPinInstallReceiver
 am broadcast -n android/com.android.server.updates.IntentFirewallInstallReceiver
 am broadcast -n android/com.android.server.updates.SELinuxPolicyInstallReceiver
 am broadcast -n android/com.android.server.updates.SmsShortCodesInstallReceiver
 am broadcast -n android/com.android.server.updates.TZInfoInstallReceiver
